services:
  bipol-app:
    build: .
    container_name: bipol-backend
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
      - "${UDP_PORT:-3333}:${UDP_PORT:-3333}/udp"
    env_file:
      - .env
    restart: unless-stopped
