services:
  bipol-app:
    build: .
    container_name: bipol-backend
    ports:
      - "3000:3000"
      - "3333:3333/udp"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
