services:
  app:
    build: .
    container_name: website_bipol_local
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
    env_file:
      - .env
    depends_on:
      - db_local
    networks:
      - local_net

  db_local:
    image: mysql:8.0
    container_name: db_bipol_local
    environment:
      MYSQL_ROOT_PASSWORD: bpl_bipol
      MYSQL_DATABASE: bipol_tracker
    ports:
      - "3307:3306"
    volumes:
      - local_db_data:/var/lib/mysql
    networks:
      - local_net

volumes:
  local_db_data:

networks:
  local_net:
    driver: bridge